import Head from "next/head";
import Banner from "../components/banner";
import Header from "../components/header";
import Portfolio from "../components/portfolio";
import Profile from "../components/profile";
import { useContext } from "react";
import { NavContext } from "../lib/context/navContext";

export enum Sections {
	banner = "banner",
	profile = "profile",
	portfolio = "portfolio",
}

export const SECTION_NAMES = {
	banner: "banner",
	profile: "profile",
	portfolio: "portfolio",
};

export default function Home() {
	const { refs } = useContext(NavContext);

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div ref={refs.banner}>
				<Banner />
			</div>
			<div ref={refs.profile}>
				<Profile />
			</div>
			<div ref={refs.portfolio}>
				<Portfolio />
			</div>
		</div>
	);
}
