import Head from 'next/head'
import Banner from '../components/banner'
import Header from '../components/header'
import Profile from '../components/profile'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Banner />
      <Profile />
    </div>
  )
}
